const fs = require('fs');
const path = require('path');
const assert = require('assert');

const root = path.resolve(__dirname, '..');
const indexHtml = fs.readFileSync(path.join(root, 'frontend', 'index.html'), 'utf8');
const scriptsJs = fs.readFileSync(path.join(root, 'frontend', 'scripts.js'), 'utf8');
const stylesCss = fs.readFileSync(path.join(root, 'frontend', 'styles.css'), 'utf8');

assert(!indexHtml.includes('竞研 <br>'), 'landing title should keep 竞研 and Agent on one line');
assert(indexHtml.includes('竞研 <span'), 'landing title should render 竞研 and Agent inline');
assert(!indexHtml.includes('中文报告'), 'landing copy should say 报告, not 中文报告');
assert(!indexHtml.includes('<a href="#form" class="btn btn-primary">开始研究</a>'), 'landing CTA should be removed');

assert(!indexHtml.includes('id="report_type"'), 'visible report type selector should be removed');
assert(!indexHtml.includes('id="tone"'), 'visible tone selector should be removed');
assert(indexHtml.includes('id="report_source"'), 'research source selector should remain visible');
assert(indexHtml.includes('id="maxSearchResults"'), 'max search results input should remain visible');
assert(indexHtml.includes('id="queryDomains"'), 'query domains input should remain visible');

assert(scriptsJs.includes('const report_type = "research_report"'), 'frontend should submit fixed research_report payload');
assert(scriptsJs.includes('const tone = "Objective"'), 'frontend should submit fixed Objective tone payload');
assert(!scriptsJs.includes('select[name="report_type"]'), 'scripts should not depend on removed report type select');
assert(!scriptsJs.includes('select[name="tone"]'), 'scripts should not depend on removed tone select');
assert(scriptsJs.includes('select[name="report_source"]'), 'scripts should still read report source');
assert(scriptsJs.includes('max_search_results: parseInt(document.getElementById(\'maxSearchResults\').value, 10) || 5'), 'scripts should still send max search results');
assert(scriptsJs.includes('input[name="query_domains"]'), 'scripts should still send query domains');

assert(scriptsJs.includes('阅读前说明'), 'report should expose a reading context summary before the report');
assert(scriptsJs.includes('reading_context'), 'report should prefer the dedicated reading context payload');
assert(scriptsJs.includes('buildLegacyReadingContext'), 'legacy reports should derive a restrained fallback from report citations');
assert(scriptsJs.includes('analysis?.source_tiers?.classified_urls'), 'legacy reports should reuse stored S/A/B/C source tiers when available');
assert(scriptsJs.includes("official: '官方来源'"), 'reading context should label official sources in user language');
assert(scriptsJs.includes("authoritative: '权威来源'"), 'reading context should label authoritative sources in user language');
assert(scriptsJs.includes("ordinary: '普通公开来源'"), 'reading context should label ordinary public sources in user language');
assert(scriptsJs.includes("weak_verification: '弱验证来源'"), 'reading context should label weak-verification sources in user language');
assert(scriptsJs.includes('authoritative_source_count'), 'reading context should expose authoritative source counts');
assert(scriptsJs.includes('ordinary_source_count'), 'reading context should expose ordinary source counts');
assert(scriptsJs.includes('weak_verification_source_count'), 'reading context should expose weak-verification source counts');
assert(scriptsJs.includes('reading-context-tier-summary'), 'expanded source overview should show the four-tier composition');
assert(stylesCss.includes('.reading-context-tier-summary'), 'four-tier source composition should have a responsive restrained layout');
assert(!scriptsJs.includes("unclassified: '未分类'"), 'reading context should never render an unclassified label');
assert(scriptsJs.includes('resolveHistoryCompetitiveAnalysis'), 'history restore should load stored competitive analysis before using a fallback');
assert(scriptsJs.includes('const analysisForReading = competitiveAnalysis || { request: getCompetitiveResearchData() }'), 'completed reports without metadata should still render a citation-based reading context');
assert(scriptsJs.includes("const reportSurface = document.getElementById('researchResultHost')"), 'reading context rendering should locate the report scroll surface');
assert(scriptsJs.includes('reportSurface.scrollTop = 0'), 'reading context should reset the report to the top so the pre-reading card is visible');
assert(scriptsJs.includes("analysisSummary.classList.add('report-reading-context-host')"), 'reading context should be hosted separately from report body');
assert(scriptsJs.includes('reportWrapper.prepend(analysisSummary)'), 'reading context should render before the formal report body');
assert(scriptsJs.includes("readingContextDetails.addEventListener('toggle'"), 'reading context should expose expandable details');
assert(!scriptsJs.includes('报告依据与可信度'), 'report should not render the oversized legacy evidence card');
assert(!scriptsJs.includes('高风险'), 'report UI should not show high-risk wording');
assert(!scriptsJs.includes('风险等级'), 'report UI should not show internal risk level labels');
assert(!scriptsJs.includes('企业级 Evaluator'), 'report UI should not expose evaluator internals');
assert(!scriptsJs.includes('Repair Loop'), 'report UI should not expose repair-loop internals');
assert(!scriptsJs.includes('plan-and-execute'), 'report UI should not expose agent paradigm internals');
assert(!scriptsJs.includes('analysis-matrix-wrap'), 'frontend should not render deterministic matrix as user report content');
assert(!scriptsJs.includes('补搜记录'), 'supplemental search logs should stay in progress, not report');
assert(scriptsJs.includes('imgElement.onerror'), 'image rendering should remove broken images');
assert(scriptsJs.includes('参考图片'), 'valid images should be labeled as reference images');
assert(stylesCss.includes('.report-reading-context'), 'reading context should have dedicated restrained UI');
assert(stylesCss.includes('.reading-context-details'), 'reading context details should use a compact disclosure layout');

assert(scriptsJs.includes('const resolveHistoryReportContent = async (entry)'), 'history restore should resolve report body before falling back to parameter-only load');
assert(scriptsJs.includes('fetch(entry.links.md)'), 'history restore should fetch markdown output when only links are stored');
assert(scriptsJs.includes('target.closest(\'a, button\')'), 'history card clicks should ignore nested action links and buttons');
assert(scriptsJs.includes('history-entry-format a'), 'history format links should stop click propagation');
assert(scriptsJs.includes('const loadResearchEntry = async (index)'), 'history restore should be async so report content can be fetched');
assert(scriptsJs.includes('这条历史只有参数，没有保存报告结果。'), 'parameter-only history entries should explain why no report appears');

assert(indexHtml.includes('class="research-app-shell"'), 'single-shell research workspace should exist');
assert(indexHtml.includes('id="researchSidebar"'), 'persistent research history sidebar should exist');
assert(indexHtml.includes('id="welcomeView"'), 'welcome view should exist');
assert(indexHtml.includes('id="setupBasicView"'), 'basic setup step should exist');
assert(indexHtml.includes('id="setupOptionsView"'), 'options setup step should exist');
assert(indexHtml.includes('id="runningView"'), 'running progress view should exist');
assert(indexHtml.includes('id="resultView"'), 'result reading view should exist');
assert(indexHtml.includes('data-research-stage="plan"'), 'running view should expose the planning stage');
assert(indexHtml.includes('data-research-stage="report"'), 'running view should expose the report stage');
assert(indexHtml.includes('id="researchToc"'), 'result view should include a report table of contents');
assert(indexHtml.includes('id="mobileSidebarToggle"'), 'mobile sidebar toggle should exist');
assert(indexHtml.includes('id="sidebarHomeButton"'), 'sidebar should expose a return-home action');
assert(indexHtml.includes('href="/static/jingyan-agent-cat-professional.png?v=3"'), 'favicon should reuse the professional cat IP');
assert(!indexHtml.includes('jingyan-agent-cat-favicon'), 'legacy childlike favicon should be removed');
assert(indexHtml.includes('/site/scripts.js?v=workbench-5'), 'workbench behavior changes should invalidate the cached script');
assert(indexHtml.includes('/site/styles.css?v=workbench-5'), 'workbench visual changes should invalidate the cached stylesheet');
assert(scriptsJs.includes('setWorkbenchView'), 'scripts should centralize workbench state transitions');
assert(scriptsJs.includes('syncTaskUrl'), 'scripts should synchronize the selected task with the URL');
assert(scriptsJs.includes("document.getElementById('sidebarHomeButton')?.addEventListener('click'"), 'home action should be wired through the workbench controller');
assert(scriptsJs.includes('renderWorkbenchHistory'), 'scripts should render grouped history in the persistent sidebar');
assert(scriptsJs.includes('buildReportToc'), 'scripts should derive a table of contents from report headings');
assert(stylesCss.includes('--workbench-accent'), 'workbench should use a restrained design token system');
assert(stylesCss.includes('.sidebar-home-button'), 'home action should have scoped sidebar styling');
assert(stylesCss.includes('@media (prefers-reduced-motion: reduce)'), 'workbench motion should respect reduced-motion preferences');
assert(scriptsJs.includes('const HISTORY_SEARCH_THRESHOLD = 8'), 'history search should use an explicit visibility threshold');
assert(scriptsJs.includes('searchControl.hidden = entries.length < HISTORY_SEARCH_THRESHOLD'), 'history search should stay hidden for short history lists');
assert(/\.sidebar-search:focus-within\s*\{[\s\S]*border-color:\s*var\(--workbench-accent\)[\s\S]*box-shadow:\s*0 0 0 3px var\(--workbench-accent-soft\)/.test(stylesCss), 'sidebar search should expose one restrained focus ring on its outer container');
assert(/\.sidebar-search input\s*\{[\s\S]*min-height:\s*0\s*!important[\s\S]*border:\s*0\s*!important[\s\S]*border-radius:\s*0\s*!important[\s\S]*background:\s*transparent\s*!important[\s\S]*box-shadow:\s*none\s*!important/.test(stylesCss), 'sidebar search input should reset the legacy default input surface');
assert(/\.sidebar-search input(?::hover|:focus|:focus-visible)[\s\S]*background:\s*transparent\s*!important[\s\S]*box-shadow:\s*none\s*!important/.test(stylesCss), 'sidebar search input states should not inherit the global nested input surface');
assert(/#researchForm\[data-workbench-step="basic"\][\s\S]*>\s*\.row\.workbench-basic-field[\s\S]*display:\s*grid/.test(stylesCss), 'basic setup rows should use a stable grid layout');
assert(/#researchForm \.competitive-research-panel\s*\{[\s\S]*box-shadow:\s*none\s*!important/.test(stylesCss), 'basic field group should not render as an extra card');
assert(stylesCss.includes('.research-options-host #researchForm'), 'options step should reset the legacy form card');
assert(/#researchForm \.dimension-option input\s*\{[\s\S]*accent-color:\s*var\(--workbench-accent\)/.test(stylesCss), 'dimension controls should use the workbench accent');
assert(/#researchForm \.dimension-option input:checked \+ span::before\s*\{[\s\S]*background:\s*var\(--workbench-accent\)/.test(stylesCss), 'dimension selection marker should use muted workbench green');
assert(/\.research-stages li\s*\{[\s\S]*grid-template-rows:\s*30px auto/.test(stylesCss), 'research stages should separate the connector line from text');
assert(/\.research-log-details summary::after\s*\{[\s\S]*content:\s*"展开"/.test(stylesCss), 'research log disclosure should expose an explicit expand affordance');
assert(/#researchProgressHost \.agent_response\s*\{[\s\S]*background:\s*#f2f5f2/.test(stylesCss), 'progress log entries should use the workbench neutral palette');
assert(indexHtml.includes('id="resultConversationPanel"'), 'result workspace should expose a dedicated follow-up conversation column');
assert(indexHtml.includes('id="resultReportPanel"'), 'result workspace should expose a dedicated report column');
assert(indexHtml.includes('id="resultColumnResizer"'), 'result workspace should expose an accessible draggable divider');
assert(!indexHtml.includes('id="voiceInputBtn"'), 'result follow-up should not expose voice recognition');
assert(!indexHtml.includes('id="sidebarStatusButton"'), 'history sidebar should not expose the redundant system status control');
assert(indexHtml.includes('id="sidebarCollapseButton"'), 'desktop history sidebar should provide a collapse control');
assert(indexHtml.includes('id="resultReportCollapseButton"'), 'report column should provide a collapse control');
assert(indexHtml.includes('data-result-pane="conversation"'), 'mobile result workspace should provide a conversation tab');
assert(indexHtml.includes('data-result-pane="report"'), 'mobile result workspace should provide a report tab');
assert(indexHtml.includes('id="resultExportMenu"'), 'report downloads should be grouped in an export menu');
assert(scriptsJs.includes("const RESULT_LAYOUT_STORAGE_KEY = 'researchResultLayout:v1'"), 'result layout state should use a versioned local storage key');
assert(scriptsJs.includes("const RESULT_CHAT_STORAGE_KEY = 'researchChatHistory:v1'"), 'task chat history should use a separate versioned local storage key');
assert(scriptsJs.includes('persistResultLayout'), 'result column collapse state should be persisted');
assert(scriptsJs.includes('applyResultConversationWidth'), 'result conversation width should be adjustable and persisted');
assert(scriptsJs.includes("resultColumnResizer.addEventListener('pointerdown'"), 'result divider should support pointer dragging');
assert(scriptsJs.includes("resultColumnResizer.addEventListener('keydown'"), 'result divider should support keyboard resizing');
assert(scriptsJs.includes('restoreTaskChatHistory'), 'task-specific follow-up messages should restore when switching reports');
assert(scriptsJs.includes('removeTaskChatHistory'), 'deleting research history should remove its task chat');
assert(scriptsJs.includes("fetch('/api/chat'"), 'report follow-up should use the dedicated chat endpoint');
assert(!scriptsJs.includes('const messageToSend = `chat ${JSON.stringify'), 'report follow-up should not reuse the research WebSocket');
assert(/\.result-workbench\s*\{[\s\S]*grid-template-columns:\s*var\(--result-conversation-width,\s*clamp\(360px,\s*46%,\s*560px\)\) 8px minmax\(360px,\s*1fr\)/.test(stylesCss), 'result workspace should default to balanced resizable conversation and report columns');
assert(/\.result-column-resizer\s*\{[\s\S]*cursor:\s*col-resize/.test(stylesCss), 'result divider should visibly afford horizontal resizing');
assert(/body\.sidebar-collapsed \.research-app-shell\s*\{[\s\S]*grid-template-columns:\s*56px minmax\(0,\s*1fr\)/.test(stylesCss), 'collapsed history should become a narrow icon rail');
assert(/\.result-workbench\.is-report-collapsed\s*\{[\s\S]*grid-template-columns:\s*minmax\(360px,\s*1fr\) 0 56px/.test(stylesCss), 'collapsed report should become a narrow icon rail');
assert(/@media \(max-width:\s*760px\)[\s\S]*\.result-mobile-tabs\s*\{[\s\S]*display:\s*grid/.test(stylesCss), 'mobile result workspace should expose pane tabs');
assert(scriptsJs.includes("const ACTIVE_RESEARCH_STORAGE_KEY = 'activeResearchTask:v1'"), 'running research recovery should use a versioned local storage key');
assert(scriptsJs.includes("data.type === 'task_accepted'"), 'frontend should replace pending state with the backend-issued task id');
assert(scriptsJs.includes("data.type === 'task_snapshot'"), 'frontend should restore a running task from a backend snapshot');
assert(scriptsJs.includes("data.type === 'task_not_found'"), 'frontend should safely clear an expired running task');
assert(scriptsJs.includes('socket.send(`subscribe ${JSON.stringify({ task_id: activeResearchTask.id })}`)'), 'frontend should resubscribe to the backend task after refresh');
assert(!scriptsJs.includes('id: `running-${Date.now()}`'), 'frontend should not fabricate a persisted running task id');
assert(!scriptsJs.includes('研究任务已停止'), 'connection loss should not tell users that detached research has stopped');

console.log('workbench_layout_check passed');
