const fs = require('fs');
const path = require('path');
const assert = require('assert');

const root = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'frontend', 'index.html'), 'utf8');
const css = fs.readFileSync(path.join(root, 'frontend', 'styles.css'), 'utf8');
const js = fs.readFileSync(path.join(root, 'frontend', 'scripts.js'), 'utf8');
const agentRepairPy = fs.readFileSync(path.join(root, 'backend', 'server', 'agent_repair.py'), 'utf8');

function has(source, pattern, message) {
  assert(pattern.test(source), message);
}

function tagById(id) {
  const match = html.match(new RegExp(`<[^>]+id="${id}"[^>]*>`));
  assert(match, `${id} should exist`);
  return match[0];
}

has(html, /class="[^"]*app-workbench[^"]*"/, 'app workbench shell should exist');
has(html, /class="[^"]*research-config-panel[^"]*"/, 'left config panel should exist');
has(html, /class="[^"]*workspace-panel[^"]*"/, 'right workspace panel should exist');
has(html, /id="workspaceProgress"/, 'research progress should live in the right workspace');
has(html, /data-workspace-tab="report"/, 'report workspace tab should exist');
has(html, /data-workspace-tab="chat"/, 'chat workspace tab should exist');
assert(/data-workspace-tab="chat"[^>]*hidden/.test(tagById('workspaceChatTab')), 'chat tab should be hidden before report finishes');
assert(/type="text"/.test(tagById('competitors')), 'competitors should remain a text input');
has(html, /class="[^"]*workbench-brand[^"]*"/, 'compact brand should live in the workbench header');
has(html, /class="[^"]*workbench-brand-avatar[^"]*"/, 'compact brand should include the cat icon');
assert(!html.includes('id="report_type"'), 'report type dropdown should be removed from visible form');
assert(!html.includes('name="report_type"'), 'report type should not be a form control');
assert(!html.includes('id="tone"'), 'tone dropdown should be removed from visible form');
assert(!html.includes('name="tone"'), 'tone should not be a form control');
has(html, /id="report_source"/, 'research source dropdown should remain');
assert(/id="workspaceProgress"[^>]*hidden/.test(tagById('workspaceProgress')), 'progress panel should be hidden before research starts');

assert(!html.includes('id="progressRail"'), 'middle progress rail should be removed');
assert(!html.includes('class="progress-rail'), 'progress rail class should be removed from markup');
assert(!html.includes('id="jsonButtonContainer"'), 'duplicate top JSON container should be removed');
assert(!html.includes('downloadLinkJsonTop'), 'duplicate top JSON button should be removed');
has(html, /id="downloadLinkJson"/, 'bottom JSON download should remain');
has(html, /data-workspace-view="report"[\s\S]*id="stickyDownloadsBar"[\s\S]*data-workspace-view="chat"/, 'download bar should live inside the report workspace, not as a global overlay');
assert(!html.includes('id="expandOutputBtn"'), 'research progress should not show a fullscreen button');
assert(!html.includes('id="expandReportBtn"'), 'research report should not show a fullscreen button');
assert(!html.includes('id="expandChatBtn"'), 'follow-up chat should not show a fullscreen button');
assert(!html.includes('id="voiceInputBtn"'), 'follow-up chat should only keep input and send controls');
assert(!html.includes('<h2><i class="fas fa-comments"'), 'follow-up chat should not use the old large heading block');

has(css, /\.app-workbench[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s+minmax\(0,\s*1fr\)/, 'desktop workbench should be 1:1');
has(css, /@media\s*\(min-width:\s*901px\)[\s\S]*html,\s*body[\s\S]*overflow:\s*hidden/, 'desktop body should not scroll');
has(css, /\.research-config-panel[\s\S]*display:\s*flex[\s\S]*flex-direction:\s*column/, 'left panel should split scroll form and fixed submit bar');
has(css, /\.research-config-panel[\s\S]*overflow:\s*hidden/, 'left panel should not let the fixed submit bar overlay scrolling content');
has(css, /\.research-config-panel\s+#researchForm[\s\S]*overflow-y:\s*auto/, 'left form content should scroll internally');
has(css, /@media\s*\(max-width:\s*900px\)[\s\S]*\.research-config-panel[\s\S]*height:\s*calc\(100svh - 108px\)[\s\S]*overflow:\s*hidden/, 'small viewports should keep the left panel footer fixed without overlay');
has(css, /\.workspace-panel[\s\S]*position:\s*relative/, 'right panel should anchor fixed bottom controls');
has(css, /\.workspace-panel[\s\S]*overflow:\s*hidden/, 'right panel shell should stay fixed while inner views scroll');
has(css, /\.workbench-brand[\s\S]*position:\s*fixed/, 'compact brand should sit in the top-left page chrome');
has(css, /\.research-submit-bar[\s\S]*flex-shrink:\s*0/, 'submit action bar should stay outside the scrollable form');
has(html, /class="[^"]*research-submit-bar[^"]*"/, 'submit action should be separated from scrollable form content');
has(css, /\.workspace-tab\.is-active[\s\S]*outline:\s*none/, 'active tabs should not use black outline');
has(css, /\.workspace-tab:focus-visible[\s\S]*outline:\s*3px solid rgba\(135,\s*225,\s*255,\s*0\.35\)/, 'tabs should retain soft focus-visible outline');
has(css, /\.workspace-progress-toggle[\s\S]*min-height:\s*0/, 'progress toggle should be compact');
assert(!css.includes('.workspace-progress-toggle::before'), 'progress toggle should not use the odd pseudo icon');
has(css, /\.workspace-progress-toggle[\s\S]*font-weight:\s*400/, 'progress toggle should not be visually heavy');
has(css, /\.workspace-progress-toggle[\s\S]*color:\s*rgba\(98,\s*111,\s*132,\s*0\.76\)/, 'progress toggle should use low-emphasis gray text');
has(css, /\.workspace-progress-toggle[\s\S]*display:\s*inline-flex[\s\S]*align-items:\s*center/, 'progress toggle text and chevron should align');
has(css, /\.workspace-progress-toggle:focus[\s\S]*outline:\s*none/, 'progress toggle should not keep a black click outline');
has(css, /\.workspace-panel\s+\.agent_response[\s\S]*background:\s*rgba\(255,\s*255,\s*255/, 'progress log entries should use the light UI theme');
has(css, /\.chat-container[\s\S]*background:\s*rgba\(255,\s*255,\s*255/, 'chat container should use light glass style');
has(css, /\.workspace-view\[data-workspace-view="chat"\]\.is-active[\s\S]*display:\s*flex/, 'chat workspace should use a full-height flex layout');
has(css, /\.chat-container[\s\S]*display:\s*flex[\s\S]*flex-direction:\s*column/, 'chat container should pin input below a scrollable message area');
has(css, /\.chat-messages[\s\S]*flex:\s*1 1 auto[\s\S]*overflow-y:\s*auto/, 'chat messages should fill remaining space and scroll internally');
has(css, /\.chat-input-container[\s\S]*max-width:\s*min\(760px,\s*calc\(100% - 32px\)\)/, 'chat input bar should be narrower than the chat panel');
has(css, /\.chat-input-container[\s\S]*margin:\s*auto auto 0/, 'chat input bar should stay at the bottom of the chat panel');
has(css, /\.chat-input-container[\s\S]*min-height:\s*56px/, 'chat input bar should stay compact');
has(css, /\.chat-input[\s\S]*height:\s*36px/, 'chat textarea should start as a compact single-line input');
has(css, /\.workspace-view\[data-workspace-view="chat"\]\.is-active[\s\S]*height:\s*100%/, 'chat workspace should use full available panel height');
has(css, /\.workspace-panel:has\(\.workspace-view\[data-workspace-view="chat"\]\.is-active\)[\s\S]*overflow:\s*hidden/, 'chat tab should prevent the whole workspace from scrolling');
has(css, /\.workspace-panel:has\(\.workspace-view\[data-workspace-view="chat"\]\.is-active\)\s+#chatMessages[\s\S]*max-height:\s*none/, 'chat messages should not inherit legacy max-height limits');
has(css, /\.chat-input-container[\s\S]*position:\s*absolute[\s\S]*bottom:\s*18px/, 'chat input should be fixed to the bottom of the workspace panel');
has(css, /\.chat-input-container[\s\S]*position:\s*fixed[\s\S]*bottom:\s*14px/, 'chat input should be fixed to the viewport bottom while scrolling');
has(css, /\.chat-message-row\.ai-row[\s\S]*display:\s*grid[\s\S]*grid-template-columns:\s*38px minmax\(0,\s*1fr\)/, 'AI chat messages should reserve space for the cat avatar');
has(css, /\.chat-ai-avatar[\s\S]*width:\s*34px/, 'AI chat avatar should use a compact cat icon');
has(css, /\.user-message[\s\S]*background:\s*rgba\(244,\s*246,\s*248,\s*0\.92\)/, 'user chat bubble should use a GPT-like light gray bubble');
has(css, /\.ai-message[\s\S]*background:\s*rgba\(255,\s*255,\s*255/, 'AI chat bubble should use light theme');
has(css, /\.chat-input[\s\S]*background:\s*rgba\(255,\s*255,\s*255/, 'chat input should use light style');
has(css, /\.chat-input-container[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s+52px/, 'chat input should only reserve space for the send button');
has(css, /\.analysis-matrix\s+td[\s\S]*color:\s*#2b313b/, 'analysis matrix cells should be readable on the light theme');
has(css, /\.analysis-matrix\s+th[\s\S]*background:\s*rgba\(135,\s*225,\s*255,\s*0\.22\)/, 'analysis matrix headers should use the light theme');
has(css, /\.analysis-matrix\s+\.matrix-found[\s\S]*color:\s*#244653/, 'found matrix cells should use readable low-saturation text');
has(css, /\.analysis-matrix\s+\.matrix-missing[\s\S]*color:\s*#b94a55/, 'missing matrix cells should use readable soft red text');
has(css, /\.report-evidence-panel[\s\S]*background:\s*rgba\(255,\s*255,\s*255/, 'report evidence panel should use the light report UI');
has(css, /\.report-evidence-note[\s\S]*color:\s*rgba\(76,\s*86,\s*108,\s*0\.78\)/, 'report evidence explainer should be visually secondary');
has(css, /\.agent-gap-list\s+li\s+span[\s\S]*background:\s*transparent\s*!important/, 'gap labels should not be rendered as hard-to-read capsules');
has(css, /\.agent-gap-list\s+li\s+span[\s\S]*font-weight:\s*800/, 'gap labels should be emphasized with bold text');
has(css, /\.agent-gap-list\s+li\s+span[\s\S]*color:\s*#176f72\s*!important/, 'gap labels should use a fresh readable accent color');
has(css, /\.progress-tool-list\s+li\s+span[\s\S]*color:\s*#1f4a5f/, 'process tool labels should stay readable on the light theme');
has(css, /\.progress-tool-list\s+li\s+span[\s\S]*background:\s*rgba\(255,\s*255,\s*255,\s*0\.92\)/, 'process tool labels should not use pale-blue-on-pale-blue highlights');
has(css, /\.sticky-downloads-bar[\s\S]*background:\s*rgba\(255,\s*255,\s*255/, 'bottom download bar should use light glass style');
has(css, /\.sticky-downloads-bar[\s\S]*position:\s*fixed/, 'download bar should be fixed to the viewport bottom');
has(css, /\.sticky-downloads-bar[\s\S]*bottom:\s*14px/, 'download bar should sit at the bottom of the viewport');
has(css, /\.sticky-downloads-bar\.is-workspace-hidden[\s\S]*display:\s*none\s*!important/, 'download bar should be hidden when the chat workspace is active');
has(css, /\.download-buttons-container[\s\S]*flex-wrap:\s*nowrap/, 'download buttons should stay on one line');
has(css, /#downloadLink\.disabled[\s\S]*display:\s*none\s*!important/, 'unavailable PDF download should be hidden');
has(css, /\.download-option-btn[\s\S]*background:\s*rgba\(255,\s*255,\s*255/, 'bottom buttons should use light pills');
has(css, /#selectedImagesContainer[\s\S]*max-height:/, 'research images should be height-constrained');
has(css, /#selectedImagesContainer\.has-valid-images/, 'research images should only show after valid images load');

assert(!js.includes('downloadLinkJsonTop'), 'JS should not update removed top JSON button');
assert(!js.includes('jsonButtonContainer'), 'JS should not show removed top JSON container');
has(js, /initWorkspaceProgress/, 'workspace progress initializer should exist');
has(js, /collapseWorkspaceProgress/, 'finish state should be able to collapse workspace progress');
has(js, /const DEFAULT_REPORT_TYPE = 'research_report'/, 'JS should fix report type to competitive research default');
has(js, /const DEFAULT_TONE = 'Objective'/, 'JS should fix tone to Objective');
assert(!js.includes('querySelector(\'select[name="report_type"]\')'), 'JS should not depend on report type select');
assert(!js.includes('querySelector(\'select[name="tone"]\')'), 'JS should not depend on tone select');
has(js, /showWorkspaceProgress/, 'JS should reveal progress only when research starts');
has(js, /hideWorkspaceProgress/, 'JS should hide progress before research starts');
has(js, /syncWorkspaceProgressVisibility/, 'workspace progress visibility should sync with active workspace tab');
has(js, /target === 'chat'[\s\S]*workspaceProgress\.hidden = true/, 'chat tab should hide workspace progress');
has(js, /let chatMessagesState = \[\]/, 'chat should track user and assistant message history');
has(js, /const WORKSPACE_SNAPSHOT_KEY = 'currentResearchWorkspace'/, 'current report workspace should use a dedicated localStorage snapshot');
has(js, /persistCurrentWorkspaceSnapshot/, 'current report and chat state should be persisted after generation and chat updates');
has(js, /restoreWorkspaceSnapshot/, 'page init should be able to restore the latest report workspace after refresh');
has(js, /clearWorkspaceSnapshot/, 'starting a new research run should clear stale workspace snapshots');
has(js, /startResearch[\s\S]*clearWorkspaceSnapshot\(\)/, 'starting a new research run should clear the previous current workspace snapshot');
has(js, /restoreChatMessages/, 'restoring workspace should include follow-up chat messages');
has(js, /activeWorkspaceTab:\s*getActiveWorkspaceTarget\(\)/, 'workspace snapshot should remember whether the user was reading the report or chatting');
has(js, /activateWorkspaceView\(snapshot\.activeWorkspaceTab === 'chat' \? 'chat' : 'report'\)/, 'workspace restore should return to the previous report/chat tab');
has(js, /localStorage\.setItem\(WORKSPACE_SNAPSHOT_KEY/, 'workspace snapshot should be saved to localStorage, not cookie-limited history');
has(js, /localStorage\.getItem\(WORKSPACE_SNAPSHOT_KEY/, 'workspace snapshot should be read from localStorage on refresh');
has(js, /restoreWorkspaceSnapshot\(\)/, 'init should attempt to restore the current workspace snapshot');
has(js, /addChatMessage\(data\.content,\s*false\);\s*[\r\n\s]*persistCurrentWorkspaceSnapshot\(\)/, 'AI chat replies should persist after being added to chat history');
has(js, /chatAiAvatar/, 'AI chat messages should render the cat avatar element');
has(js, /setDownloadBarVisibilityForWorkspace/, 'download bar visibility should follow the active workspace tab');
has(js, /getCurrentChatReportContext/, 'chat should collect the full current report context');
has(js, /buildChatPayload/, 'chat should build a report-aware payload');
has(js, /report:\s*getCurrentChatReportContext\(\)/, 'chat payload should include the current report');
has(js, /messages:\s*outgoingMessages/, 'chat payload should include chat history');
assert(!js.includes('initSpeechRecognition(voiceInputBtn, chatInput)'), 'chat should not initialize the removed voice input control');
has(js, /candidate_official_source_found:\s*'找到候选官方来源'/, 'candidate official-source enum should be translated for users');
has(js, /formatGapReasonForUser/, 'internal evaluator reasons should be rewritten into user-readable copy');
has(js, /renderGapItem\(gap\)/, 'gap rendering should use a dedicated user-facing formatter');
has(js, /renderReportEvidencePanel/, 'results should include a separate report evidence and credibility panel');
has(js, /getReportReferencedUrls/, 'evidence panel should only show sources referenced by the final report');
has(js, /reportReferencedUrlKeys\.has\(key\)/, 'source candidates should be filtered against URLs actually referenced by the report');
has(js, /filterReportRelatedGaps/, 'evidence panel should only show uncertainty related to report content');
assert(!js.includes('overall_risk'), 'user-facing evidence panel should not show internal risk levels');
assert(!js.includes('paradigm'), 'user-facing evidence panel should not show internal agent strategy names');
assert(!js.includes('plan-and-execute'), 'user-facing evidence panel should not expose internal agent strategy text');
assert(!js.includes('analysis-matrix-wrap'), 'post-processed competitive matrix should not be rendered in the user result area');
assert(!js.includes('analysis-subqueries'), 'planner subquestions should not be rendered in the user result area');
assert(!js.includes('agent-trace-panel'), 'agent process details should not be rendered in the user result area');
has(js, /renderToolCallsInProgress/, 'tool call details should be rendered in the research progress area');
has(js, /renderToolCallsInProgress[\s\S]*workspaceProgressStarted = true[\s\S]*syncWorkspaceProgressVisibility\(\)/, 'tool call progress records should keep the progress panel available after restore');
assert(!js.includes('<div class="agent-tool-list">'), 'tool call details should not be rendered inside the report summary');
has(js, /gap\.user_message\s*\|\|\s*gap\.userMessage\s*\|\|\s*gap\.user_facing_message/, 'frontend should prefer backend/model user-readable gap copy');
has(js, /gap\.suggested_action\s*\|\|\s*gap\.suggestedAction/, 'frontend should display backend/model suggested actions when provided');
assert(!js.includes('<span>${escape(gap.type)}</span>'), 'raw internal gap type fields should not be shown to users');
assert(!js.includes('企业级 Evaluator 结果'), 'enterprise evaluator heading should be rewritten for users');
assert(!js.includes('Evaluator 硬门槛'), 'hard gate heading should be rewritten for users');
assert(!js.includes('Evaluator 软风险'), 'soft warning heading should be rewritten for users');
assert(!js.includes('Evaluator 发现的缺口'), 'gap heading should be rewritten for users');
assert(!js.includes('Repair Loop 闭环结果'), 'repair-loop heading should be rewritten for users');
has(js, /报告依据与可信度/, 'report evidence heading should be user-facing');
has(js, /正式报告引用的来源/, 'source section should make clear it only covers report citations');
has(js, /报告中需要谨慎确认的信息/, 'uncertainty section should be tied to report content');
has(js, /需要留意的口径/, 'time/source caveats should be presented as user-readable scope notes');
assert(!js.includes('来源与时效提示'), 'caveats should not be a separate confusing risk section');
has(js, /imgElement\.onerror[\s\S]*imgElement\.remove\(\)/, 'broken research images should be removed');
has(js, /validImageCount[\s\S]*has-valid-images/, 'image strip should only be shown when at least one image loads');
has(agentRepairPy, /"user_message":/, 'backend gap payload should include user-readable copy');
has(agentRepairPy, /"suggested_action":/, 'backend gap payload should include a user-facing suggested action');
has(agentRepairPy, /def _gap_user_message/, 'backend should centralize user-facing gap copy generation');

console.log('workbench layout contract passed');
